version: "3"
services:
  web:
    image: nginx
    ports:
      - 8000:80
    command:
    - /bin/sh
    - -c
    - |
      sed -i \
        "/server_name.*/a index index.html;" \
        /etc/nginx/conf.d/default.conf && \
      exec nginx -g "daemon off;"
    volumes:
      - ./src:/usr/share/nginx/html